export const Members = [
  {
    id: 1,
    member_name: "Orn SivEng",
    member_title: "Team leader",
    member_image: "/team_members/siveng.jpg",
    member_github: "https://github.com/SivEngOrn",
    member_linkedin: "https://www.linkedin.com/in/siveng-orn/",
    member_facebook: "https://www.facebook.com/siveng.orn",
  },
  {
    id: 1,
    member_name: "Sroeun Doungchan",
    member_title: "Fullstack Developer",
    member_image: "/team_members/doungchan.jpg",

    member_github: "https://github.com/DoungChan",
    member_linkedin: "https://www.linkedin.com/in/doungchan-sroeun-9524a8253/",
    member_facebook: "https://www.facebook.com/doung.chan.3950/",
  },
  {
    id: 1,
    member_name: "Ney Senrith",
    member_title: "Fullstack Developer",
    member_image: "/team_members/Ney Senrith_B.png",
    member_github: "https://github.com/Senrith3",
    member_linkedin: "#",
    member_facebook: "https://www.facebook.com/senrith.ney.5",
  },
  {
    id: 1,
    member_name: "Lock Borethdevid",
    member_title: "Frontend Developer",
    member_image: "/team_members/Lock Boreth Devid_A.png",
    member_github: "https://github.com/lockborethdevid",
    member_linkedin: "https://www.linkedin.com/in/lock-boreth-devid-6b0298225/",
    member_facebook: "https://www.facebook.com/profile.php?id=100089213722090",
  },
  {
    id: 1,
    member_name: "Oun Visidhreach",
    member_title: "Frontend Developer",
    member_image: "/team_members/Oun Visidhreach_B.png",
    member_github: "https://github.com/OunVisidhreach",
    member_linkedin: "#",
    member_facebook: "https://www.facebook.com/chris.ivan.3532",
  },
  {
    id: 1,
    member_name: "San Vivorth",
    member_title: "Backend Developer",
    member_image: "/team_members/San Vivorth_A.png",
    member_github: "https://github.com/S-Vivorth",
    member_linkedin: "#",
    member_facebook: "https://www.facebook.com/san.vivorth",
  },
  {
    id: 1,
    member_name: "Sor Panharith",
    member_title: "Backend Developer",
    member_image: "/team_members/Sor Panharith_A.png",
    member_github: "https://github.com/sor-panharith",
    member_linkedin:
      "https://www.linkedin.com/in/panharith-sor-850aa1245?fbclid=IwAR1khXyL2SfytjkJY5YaSDpZfWVcVChHg4kVsNyx3jNz9iG8PQgnIsgBfO4",
    member_facebook: "https://www.facebook.com/sor.panharith16",
  },
];
